import { Sneaker } from '@/types/Sneaker';
import { ContactInfo } from '@/types/ContactInfo';
import { AboutContent } from '@/types/AboutContent';

export const sneakersData: Sneaker[] = [
  {
    id: 'nike-sb-dunk-low-paris',
    imageSrc: '/images/paris.avif',
    imageAlt: 'Nike SB Dunk Low Paris',
    title: 'Nike SB Dunk Low "Paris"',
    badgeText: 'ULTRA RARE',
    badgeTailwindColor: 'bg-error',
    description: 'Extrémně vzácná edice inspirovaná uměleckou scénou Paříže.',
    tags: ['Dunk SB', 'Limited', 'Art'],
  },
  {
    id: 'aj1-off-white-chicago',
    imageSrc: '/images/chicago.avif',
    imageAlt: 'Air Jordan 1 Retro High OG x Off-White Chicago',
    title: 'AJ1 x Off-White "Chicago"',
    badgeText: 'GRAIL',
    badgeTailwindColor: 'bg-success',
    description: 'Jedna z nejžádanějších kolaborací Virgil Abloh x Jordan Brand.',
    tags: ['Jordan 1', 'Off-White', 'Kolekce'],
  },
  {
    id: 'nike-air-mag-bttf',
    imageSrc: '/images/future.avif',
    imageAlt: 'Nike Air Mag Back to the Future',
    title: 'Nike Air Mag "Back to the Future"',
    badgeText: 'ICONIC',
    badgeTailwindColor: 'bg-info',
    description: 'Futuristické boty s automatickým šněrováním z filmu Návrat do budoucnosti.',
    tags: ['Film', 'Technologie', 'Limitovaná edice'],
  },
  {
    id: 'nike-sb-dunk-low-pigeon',
    imageSrc: '/images/pigeon.avif',
    imageAlt: 'Nike SB Dunk Low Staple Pigeon',
    title: 'Nike SB Dunk Low "Pigeon"',
    badgeText: 'LEGENDARY',
    badgeTailwindColor: 'bg-warning',
    description: 'Kontroverzní release, který v roce 2005 rozpoutal šílenství v ulicích NYC.',
    tags: ['Dunk SB', 'New York', 'Historie'],
  },
  {
    id: 'af1-travis-scott-sail',
    imageSrc: '/images/travissail.avif',
    imageAlt: 'Nike Air Force 1 Low Travis Scott Sail',
    title: 'AF1 x Travis Scott "Sail"',
    badgeText: 'COLLAB',
    badgeTailwindColor: 'bg-error',
    description: 'Vyhledávaná kolaborace Air Force 1 s raperem Travisem Scottem.',
    tags: ['Air Force 1', 'Travis Scott', 'Hyped'],
  },
  {
    id: 'aj4-kaws-grey',
    imageSrc: '/images/kaws.avif',
    imageAlt: 'Air Jordan 4 Retro x Kaws Grey',
    title: 'AJ4 x KAWS "Grey"',
    badgeText: 'ART EDITION',
    badgeTailwindColor: 'bg-success',
    description: 'Umělecká kolaborace Air Jordan 4 s proslulým umělcem KAWS.',
    tags: ['Jordan 4', 'KAWS', 'Street Art'],
  },
  {
    id: 'nike-air-yeezy-2-red-october',
    imageSrc: '/images/kanye.avif',
    imageAlt: 'Nike Air Yeezy 2 Red October',
    title: 'Nike Air Yeezy 2 "Red October"',
    badgeText: 'HISTORIC',
    badgeTailwindColor: 'bg-info',
    description: 'Poslední a nejtajemnější release Kanyeho s Nike, vzácný kousek.',
    tags: ['Yeezy', 'Kanye West', 'OG'],
  },
  {
    id: 'nike-sb-dunk-high-skunk',
    imageSrc: '/images/skunk.avif',
    imageAlt: 'Nike SB Dunk High Skunk',
    title: 'Nike SB Dunk High "Skunk"',
    badgeText: 'FIRE ASF',
    badgeTailwindColor: 'bg-warning',
    description: 'Kultovní Dunk High inspirovaný konopím, oblíbený mezi sběrateli.',
    tags: ['Dunk SB', '420', 'Rare'],
  },
  {
    id: 'aj11-concord',
    imageSrc: '/images/concord.avif',
    imageAlt: 'Nike Air Jordan 11 Retro Concord',
    title: 'AJ11 "Concord"',
    badgeText: 'BASKETBALL LEGEND',
    badgeTailwindColor: 'bg-error',
    description: 'Ikonická bota, ve které Michael Jordan hrál po návratu do NBA.',
    tags: ['Jordan 11', 'NBA', 'MJ'],
  },
  {
    id: 'air-max-1-atmos-elephant',
    imageSrc: '/images/elephant.avif',
    imageAlt: 'Nike Air Max 1 Atmos Elephant',
    title: 'Air Max 1 x Atmos "Elephant"',
    badgeText: 'COLLAB',
    badgeTailwindColor: 'bg-success',
    description: 'Slavná kolaborace s japonským obchodem Atmos, známá pro svůj "elephant print".',
    tags: ['Air Max 1', 'Atmos', 'Print'],
  },
  {
    id: 'nike-sb-dunk-low-freddy-krueger',
    imageSrc: '/images/freddy.avif',
    imageAlt: 'Nike SB Dunk Low Freddy Krueger',
    title: 'Nike SB Dunk Low "Freddy Krueger"',
    badgeText: 'HORROR',
    badgeTailwindColor: 'bg-info',
    description: 'Velmi vzácný a kontroverzní model inspirovaný filmovou postavou.',
    tags: ['Dunk SB', 'Horror', 'Unreleased'],
  },
  {
    id: 'af1-louis-vuitton',
    imageSrc: '/images/lv.avif',
    imageAlt: 'Nike Air Force 1 Low Louis Vuitton',
    title: 'AF1 x Louis Vuitton',
    badgeText: 'LUXURY',
    badgeTailwindColor: 'bg-warning',
    description: 'Exkluzivní a luxusní kolaborace mezi Nike a Louis Vuitton.',
    tags: ['Air Force 1', 'Louis Vuitton', 'Haute Couture'],
  },
];

export const contactInfoData: ContactInfo = {
  address: {
    street: '123 Sneaker St.',
    city: 'Sneaker City',
    zip: 'SC 12345',
    country: 'Country',
  },
  phone: '+1 (555) 987-6543',
  email: 'info@sneakergallery.com',
  businessHours: [
    { days: 'Monday - Friday', time: '9:00 AM - 5:00 PM' },
    { days: 'Saturday', time: '10:00 AM - 2:00 PM' },
    { days: 'Sunday', time: 'Closed' },
  ],
  mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5064.271306930894!2d165.96307429607987!3d-50.60601681204794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xa9b37960d3cdddd7%3A0xbd1bca4ab10f2187!2sDisappointment%20Island!5e0!3m2!1sen!2scz!4v1749138291349!5m2!1sen!2scz',
};

export const aboutContent: AboutContent = {
  heroTitle: 'About Our Sneaker Gallery',
  heroParagraph: 'Welcome to the ultimate destination for sneaker enthusiasts! We are passionate about curating and showcasing the most iconic, rare, and legendary sneakers from around the world.',
  passionVisionTitle: 'Our Passion & Vision',
  passionVisionParagraph1: 'Our journey began with a simple love for sneakers and the stories they tell. From the groundbreaking designs to the cultural impact, each pair holds a unique place in history. We strive to be a comprehensive resource, connecting collectors and fans with the history and artistry of footwear.',
  passionVisionParagraph2: 'We believe that sneakers are more than just shoes; they are a form of self-expression, a piece of art, and a reflection of diverse cultures. Our vision is to foster a vibrant community where this passion can be shared and celebrated.',
  valuesTitle: 'Our Core Values',
  valueAuthenticityTitle: 'Authenticity',
  valueAuthenticityDescription: 'We are committed to showcasing only genuine and verified sneakers.',
  valueAuthenticityTag: 'Trust',
  valueCommunityTitle: 'Community',
  valueCommunityDescription: 'Fostering a passionate and inclusive space for all sneakerheads.',
  valueCommunityTag: 'Share',
  valuePassionTitle: 'Passion',
  valuePassionDescription: 'Driven by an unwavering love for sneaker culture and history.',
  valuePassionTag: 'Love',
  ctaTitle: 'Join Our Sneaker Journey!',
  ctaParagraph: 'Explore our extensive gallery, learn about the stories behind each pair, and connect with fellow enthusiasts.',
};